account/urls.py
from django.conf.urls import url
from account import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm

from .views import (
    UserDetailView
)
app_name = 'account'
urlpatterns=[
    #url(r'^$',views.home),
    url(r'^login/$',login, {'template_name': 'account/login.html'}, name='login',),
    url(r'^logout/$',logout,{'template_name': 'account/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<pk>\d+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, name='password_reset'),
    url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name='password_reset_confirm'),
    #url(r'^(?P<username>[\w.@+-]+)/$', UserDetailView.as_view(), name='detail'),
    #url(r'^change-password/$', views.change_password, name='change_password'),﻿
]

story/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^$', views.story_list, name='story_list'),
    url(r'^stories/$', views.story_list, name='story_list'),
    url(r'^storyauthor/(?P<pk>\d+)$', views.StoryListbyAuthorView.as_view(), name='storys_by_author'),
    url(r'^storyauthors/$', views.StoryAuthorListView.as_view(), name='storyauthors'),
    #url(r'^storyauthor/(?P<pk>[0-9]+)/$', views.StoryListbyAuthorView, name='storys_by_author'),
    url(r'^story/(?P<pk>[0-9]+)/$', views.story_detail, name='story_detail'),
    url(r'^story/new/$', views.story_new, name='story_new'),
    url(r'^story/(?P<pk>[0-9]+)/edit/$', views.story_edit, name='story_edit'),
    #url(r'^like/$', views.story_like, name='like'),
    url(r'^like-story/$', views.like_count_story, name='like_count_story'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='cetegory'),
    url(r'^search/$', views.search, name='search'),
    url(r'^helloo/$', views.helloo_world, name='helloo_world'),

]

textory/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from account import views
from story import views
from django.contrib.auth.views import login, logout
from textory import views
from story.views import hello_world
from account.views import UserDetailView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^profiles/', include('account.urls', namespace='profiles')),
    url(r'', include('story.urls')),
    url(r'^$', hello_world),
    #url(r'^tags_input/', include('tags_input.urls', namespace='tags_input')),
    #url(r'^(?P<username>[\w.@+-]+)/$', UserDetailView.as_view(), name='detail'),
]

story/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User


class StoryAuthor(models.Model):
    """
    Model representing a author.
    """
    #user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    #bio = models.TextField(max_length=400, help_text="Enter your bio details here.")

    def get_absolute_url(self):
        """
        Returns the url to access a particular story_author instance.
        """

        return reverse('storys_by_author', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username

#class Tag(models.Model):
#    name = models.CharField(max_length=20)
#    slug = models.SlugField(unique=True)

#    def __str__(self):
#        return self.name

#    def get_absolute_url(self):
#        return reverse('story:tag_detail', kwargs={'tag_name': self.slug})

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class ThingAdjective(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Story(models.Model):
    author = models.ForeignKey(StoryAuthor, related_name='storys',null=True)
    #author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='storys',null=True)
    #author = models.ForeignKey(User, related_name='storys',null=True)

    category = models.ForeignKey(Category,null=True)

    adjective_t = models.ForeignKey(ThingAdjective,null=True)
    likes = models.PositiveIntegerField(default=0)

    @property
    def total_likes(self):
        return self.likes.count()

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='story_liked',
                                        blank=True)

    sb_thing = models.CharField(max_length=50,null=True)
    sb_story = models.CharField(max_length=150,null=True)
    sb_name = models.CharField(max_length=30,null=True)

    #create_at = models.DateTimeField(auto_now_add=True,null=True)
#    tags = models.ManyToManyField(Tag, blank=True, related_name='tags_story')
    #tags = models.CharField('Tag', blank=True)




    SB_GENDER = (
        ('他','他'),
        ('她','她'),
        ('它','它'),
    )
    sb_gender = models.CharField(max_length = 100,null=True,choices = SB_GENDER, )

    SB_ADV = (
        ('有點','有點'),
        ('非常','非常'),
        ('蠻','蠻'),
        ('超級','超級'),
        ('史上無敵','史上無敵'),
    )
    sb_adv = models.CharField(max_length = 100,null=True,choices = SB_ADV)

    SB_ADJ = (
        ('humor','humor'),
        ('奇怪','奇怪'),
        ('白目','白目'),
        ('白痴','白痴'),
        ('有病','有病'),
        ('自戀','自戀'),
        ('搞笑','搞笑'),
        ('孤僻','孤僻'),
        ('嚴肅','嚴肅'),
        ('無趣','無趣'),
        ('奇耙','奇耙'),
        ('可怕','可怕'),
        ('笨蛋','笨蛋'),
        ('健忘','健忘'),
        ('厲害','厲害'),
        ('正常','正常'),
        ('懶惰','懶惰'),
    )
    sb_adj = models.CharField(max_length = 100,null=True,choices = SB_ADJ)

    SB_ABOUT = (
        ('很喜歡','很喜歡'),
        ('不喜歡','不喜歡'),
        ('不吃','不吃'),
        ('討厭','討厭'),
        ('怕','怕'),
        ('常常','常常'),
        ('很會','很會'),
        ('曾經','曾經'),
    )
    sb_about = models.CharField(max_length = 100,null=True,choices = SB_ABOUT)

    WHO = (
        ('我們','我們'),
        ('他','他'),
        ('她','她'),
        ('它','它'),
    )
    who = models.CharField(max_length = 100,null=True,choices = WHO)

    STH_ADJ = (
        ('扯','扯'),
        ('蠢','蠢'),
        ('煩','煩'),
        ('北七','北七'),
        ('北爛','北爛'),
        ('誇張','誇張'),
        ('有趣','有趣'),
        ('好笑','好笑'),
        ('丟臉','丟臉'),
        ('瘋狂','瘋狂'),
        ('誇張','誇張'),
        ('無聊','無聊'),
        ('幼稚','幼稚'),
        ('難忘','難忘'),
        ('開心','開心'),
    )
    sth_adj = models.CharField(max_length = 100,null=True,choices = STH_ADJ)

    ITJCTS = (
        ('哎','哎'),
        ('哈哈','哈哈'),
        ('呵呵','呵呵'),
        ('顆顆','顆顆'),
        ('嘿丟','嘿丟'),
    )
    itjcts = models.CharField(max_length = 100,null=True,choices = ITJCTS)

    MARK = (
        ('~','~'),
        ('!','!'),
        ('!!!','!!!'),
        ('XD','XD'),
        ('>///<','>///<'),
        ('^^','^^'),
        (':)',':)'),
        ('。','。'),
    )
    mark = models.CharField(max_length = 100,null=True,choices = MARK)

    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.sb_name

    def get_like_url(self):
        return reverse("storys:like-toggle", kwargs={"slug": self.slug})

    def get_api_like_url(self):
        return reverse("posts:like-api-toggle", kwargs={"slug": self.slug})

story/forms.py
from django import forms
from .models import Story, Category

class StoryForm(forms.ModelForm):
    sb_thing = forms.CharField(widget=forms.TextInput(attrs={'class':'abc1 el-input__inner el-input__inner_m', 'placeholder': '字數上限30字'}))
    sb_story = forms.CharField(widget=forms.TextInput(attrs={'class':'abc2 el-input__inner el-input__inner_m', 'placeholder': '字數上限30字'}))
    sb_name = forms.CharField(widget=forms.TextInput(attrs={'class':'abc3 el-input__inner el-input__inner_s', 'placeholder': '輸入人名'}))

    #tags = forms.ModelMultipleChoiceField(
    #    to_field_name='slug',
    #    required=False,
    #    help_text=('Separate by comma to add more than once, or select from available tags'),
    #    queryset=Tag.objects.all(),
    #    widget=forms.SelectMultiple(attrs={
    #        'placeholder': ('Additional tags'),
    #        'class': 'el-select el-input__inner'
    #    })
    #)
    #tagsinput = forms.CharField(widget=forms.TextInput(attrs={'class':'el-dropdown-menu slot="dropdown"'}))
    #tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all())
    #tagsinput = forms.CharField(widget=forms.TextInput(attrs={'data-role':'tagsinput'}))

    def __init__(self, *args, **kwargs):
         super(StoryForm, self).__init__(*args, **kwargs)
         #self.fields['first_name'].widget.attrs.update({'autofocus': 'autofocus'})

         #remove labels for fields
         for field_name in self.fields:
            field = self.fields.get(field_name)
            #field.widget.attrs['placeholder'] = field.label
            field.label =''

    class Meta:
        model = Story
        fields = (
            'sb_gender',
            'sb_adv',

            'sb_about',
            'sb_thing',
            'who',

            'sb_story',
            'itjcts',
            'sb_name',
            'mark',
            'category',
            'adjective_t'
        )
    #def clean(self):
        # this condition only if the POST data is cleaned, right?
    #    cleaned_data = super(StoryForm, self).clean()
    #    print(cleaned_data.get('tags')) # return queryset of tags

story/views.py
from django.views.generic.list import ListView
from django.shortcuts import render
from django.utils import timezone
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .models import Story, StoryAuthor, Category, ThingAdjective
from .forms import StoryForm
from django.forms import ModelChoiceField
from django.http import HttpResponse
from django.views import generic
#from django.views.generic import ListView
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response


#def story_list(request):
#    return render(request, 'story/story_list.html')
def hello_world(request):
    return render(request, 'story/hello.html',)

def helloo_world(request):
    return render(request, 'story/helloo.html',)

def story_list(request):
    storys = Story.objects.filter(created_date__lte=timezone.now()).order_by('created_date')

    #query = request.GET.get("q")
    #if query:
    #    queryset_list = queryset_list.filter(category__icontains=query)
    return render(request, 'story/story_list.html', {'storys':storys})

class StoryListbyAuthorView(generic.ListView):

    """
    Generic class-based view for a list of blogs posted by a particular StoryAuthor.
    """
    model = Story
    template_name = 'story/story_list_by_author.html'

    def get_queryset(self):
        """
        Return list of Story objects created by StoryAuthor (author id specified in URL)
        """
        id = self.kwargs['pk']
        target_author=get_object_or_404(StoryAuthor, pk = id)
        return Story.objects.filter(author=target_author)

    def get_context_data(self, **kwargs):
        """
        Add StoryAuthor to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(StoryListbyAuthorView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['author'] = get_object_or_404(StoryAuthor, pk = self.kwargs['pk'])
        return context

class StoryAuthorListView(generic.ListView):
    """
    Generic class-based view for a list of bloggers.
    """
    model = StoryAuthor

def story_detail(request, pk):
    story = get_object_or_404(Story, pk=pk)
    #story_id = request.POST.get('id')
    story_id = story.pk
    liked = False
    if request.session.get('has_liked_'+str(story_id), liked):
        liked = True
        print("liked {}_{}".format(liked, story_id))
    context = {'story':story, 'liked': liked}
    return render(request, 'story/story_detail.html', {'story': story})


def story_new(request):
    if request.method == "POST":
       form = StoryForm(request.POST)
       #form.StoryAuthor = request.user
       if form.is_valid():
           story = form.save(commit=False)
           story.author, _ = StoryAuthor.objects.get_or_create(user=request.user)
           #StoryAuthor = request.user
           story.created_date = timezone.now()
           story.save()
           return redirect('story_detail', pk=story.pk)
    else:
        form = StoryForm()
    return render(request, 'story/story_create.html', {'form': form})

def story_edit(request, pk):
    story = get_object_or_404(Story, pk=pk)
    if request.method == "POST":
        form = StoryForm(request.POST, instance=story)
        if form.is_valid():
            story = form.save(commit=False)
            StoryAuthor = request.user
            #story.author = request.user
            story.created_date = timezone.now()
            story.save()
            return redirect('story_detail', pk=story.pk)
    else:
        form = StoryForm(instance=story)
    return render(request, 'story/story_edit.html', {'form': form})


def like_count_story(request):
    liked = False
    if request.method == 'GET':
        story_id = request.POST.get('id')
        story = Story.objects.get(id=int(story_id))
        if request.session.get('has_liked_'+story_id, liked):
            print("unlike")
            if story.likes > 0:
                likes = story.likes - 1
                try:
                    del request.session['has_liked_'+story_id]
                except KeyError:
                    print("keyerror")
        else:
            print("like")
            request.session['has_liked_'+story_id] = True
            likes = story.likes + 1
    story.likes = likes
    story.save()
    return HttpResponse(likes, liked)


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    storys = Story.objects.filter(category=cate)
    return render(request, 'story/story_list.html', {'storys': storys})


class CategoryView(ListView):
    model = Story
    template_name = 'story/story_list.html'
    context_object_name = 'storys'

    #def get_queryset(self):
    #    id = self.kwargs['pk']
    #    p=get_object_or_404(PersonAdjective, pk = id)
    #    return Story.objects.filter(person_adjective=p)
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

def search(request):
    query = request.GET.get('q')
    error_msg = ''

    if not query:
        error_msg = '请输入关键词'
        return render(request, 'story/story_list.html', {'error_msg': error_msg})

    storys = Story.objects.filter(Q(category__icontains=query) | Q(sb_name__icontains=query))
    return render(request, 'story/story_list.html', {'error_msg': error_msg,
                                               'storys': storys})

#@login_required
#@require_POST
#def story_like(request):
#    story_id = request.POST.get('id')
#    action = request.POST.get('action')
#    if story_id and action:
#        try:
#            story = Story.objects.get(id=story_id)
#            if action == 'like':
#                story.users_like.add(request.user)
#            else:
#                story.users_like.remove(request.user)
#            return JsonResponse({'status':'ok'})
#        except:
#            pass
#    return JsonResponse({'status':'ko'})

story/templates/story/back.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="/">TEXTORY</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'account:view_profile' %}">Profile</a></li>
                    <li><a href="{% url 'story_new' %}">Add Story</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'account:logout' %}">Log out</a></li>
                </ul>
                {% else %}

                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'account:login' %}">Login</a></li>
                  <li><a href="{% url 'account:register' %}">Register</a></li>
                </ul>
                {% endif %}
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
        </div>
        {% block body %}
            <h1>Base</h1>
        {% endblock %}
    </body>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

story/templates/story/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load story_tags %}
<html prefix='og: http://ogp.me/ns#'>
    <head>
        <title>Textory</title>
        <link rel="stylesheet" href="{% static 'css/story.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="630">
        <meta property="og:image" content="https://www.textory.tw/static/img/post.png">

        <meta property="og:type" content="website">
        <meta property="og:title" content="什麼是 朋友 是什麼？">
        <meta property="og:description" content="朋友就是幫你把你的奇聞軼事爆料出來，娛樂大家用的，只要你是有朋友的人，你也可以成為黃金爆料使者!!!">
        <meta property="og:image" content="https://www.textory.tw/static/img/post.png">
        <meta property="og:site_name" content="Textory">
        <meta property="fb:app_id" content="1877568685892013">


        <script
        src="http://code.jquery.com/jquery-3.2.1.js"
        integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
        crossorigin="anonymous"></script>

        {% block head %}
        <title>Base</title>
        {% endblock %}

        <style>
        #header {
            width: 100%;
            height: 60px;
            position: fixed;
            
            overflow: auto;
            background: #fff;
            transition: all 0.5s linear;
            padding: 0;
        }

        #header.active {
             box-shadow: 0 0 10px rgba(0,0,0,0.4);
        }

        #id_wrapper {
          min-height: 100%;
          position: relative;
          margin-top: 100px;
        }
        </style>
    </head>
    <body>
      <div class="page-wrapper">
        <nav id="sidebar" class="sidebar-wrapper">
              <div class="sidebar-content">
                <a href="#" id="toggle-sidebar"><i class="fa fa-bars"></i></a>
                <div class="sidebar-brand">
                    <a href="#">pro sidebar</a>
                </div>
                <div class="sidebar-header">
                    <div class="user-info">
                        <span class="user-name">Jhon</span>
                        <span class="user-role">Administrator</span>
                    </div>
                </div><!-- sidebar-header  -->
                <div class="sidebar-search">
                    <div>
                        <div class="input-group">
                            <input type="text" class="form-control search-menu" placeholder="Search for...">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        </div>
                    </div>
                </div><!-- sidebar-search  -->
                <div class="sidebar-menu">
                    <ul>
                        <li class="header-menu"><span>Category</span></li>
                        <li><a  href="#" ><i class="fa fa-check"></i><span>Menu 1</span></a></li>
                        <li><a href="#"><i class="fa fa-check"></i><span>Menu 2</span></a></li>
                        <li><a href="#"><i class="fa fa-check"></i><span>Menu 3</span></a></li>
                        <li><a href="#"><i class="fa fa-check"></i><span>Menu 4</span></a></li>
                        <li class="header-menu"><span>Types</span></li>
                        <li><a href="#"><i class="fa fa-check"></i><span>Menu 1</span></a></li>
                        <li><a href="#"><i class="fa fa-check"></i><span>Menu 2</span></a></li>
                        <li><a href="#"><i class="fa fa-check"></i><span>Menu 3</span></a></li>
                        <li><a href="#"><i class="fa fa-check"></i><span>Menu 4</span></a></li>
                    </ul>
                   </div><!-- sidebar-menu  -->
                </div><!-- sidebar-content  -->
            </nav><!-- sidebar-wrapper  -->


        <main class="page-content">
        <div id="header">
          <a href="/" class="header-nav-logo"><img src="{% static 'img/textory_logo.png' %}"></a>
          <nav class="header-nav">

          <ul class="header-nav-list">
          {% if user.is_authenticated %}
            <li><a class="button_blank button nav-btn" href="{% url 'account:logout' %}">登出</a></li>
          {% else %}
            <li><a class="button_blank button nav-btn" href="{% url 'account:login' %}">登入</a></li>
            <li><a class="button_blank button nav-btn" href="{% url 'account:register' %}">註冊</a></li>
          {% endif %}
            <li><a class="button" href="{% url 'story_new' %}"><i class="fa fa-pencil" aria-hidden="true"></i>寫故事</a></li>
          </ul>
        </nav>
        </div>
        {% block body %}
        <h1>Base</h1>
        {% endblock %}
        </main>

        <footer class="footer">
          <div class="footer_description_box--06">
            <div class="container footer_container">
              <span class="footer_copyright footer_copyright--06">© yuminH, 2017</span>
            </div>
          </div>
        </footer>
      </div>
      <script src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
      <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <script src="{% static 'js//jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
    </body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
    <script>
      var csrftoken = $.cookie('csrftoken');
      function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
    });

      $(document).ready(function(){
        {% block domready %}
        {% endblock %}
        });
    </script>

    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <!-- 引入组件库 -->
    <script src="https://unpkg.com/element-ui/lib/index.js"></script>

    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '1877568685892013',
          xfbml      : true,
          version    : 'v2.11'
        });
        FB.AppEvents.logPageView();
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "https://connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>

story/templates/story/story_forms.html
{% extends 'story/base.html' %}

{% block content %}
    <h1>New story</h1>

    <form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.sb_name }}

    <button type="submit" class="save btn btn-default">Save</button>
    </form>



    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}